test_number: 11
camera:
  collection:
    exposure: 50000
    gain: 1
    delay: 0
IR_LED:
  frequency: 100
  duty: 60

Optogenetic_LEDs:
  initial_delay: 8
  flash_length: 5
  frequency: 100
  duty: 100