IR_LED:
  duty: 60
  frequency: 100
Optogenetic_LEDs:
  duty: 100
  flash_length: 5
  frequency: 100
  initial_delay: 8
camera:
  delay: 0
  exposure: 50000
  gain: 1
  record_time: 30
test_number: 11
