test_number: 0
camera:
  collection:
    exposure: 50000
    gain: 1
    delay: 0.35
IR_LED:
  frequency: 1000
  duty: 60

Optogenetic_LEDs:
  initial_delay: 4
  flash_length: 5
  frequency: 1000
  duty: 100